/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i MetaTypes.h -p udisks2_mountpoints_interface udisks2_mountpoints_interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef UDISKS2_MOUNTPOINTS_INTERFACE_H
#define UDISKS2_MOUNTPOINTS_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "MetaTypes.h"

/*
 * Proxy class for interface org.freedesktop.UDisks2.Filesystem
 */
class OrgFreedesktopUDisks2FilesystemInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.UDisks2.Filesystem"; }

public:
    OrgFreedesktopUDisks2FilesystemInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopUDisks2FilesystemInterface();

    Q_PROPERTY(ByteArrayList MountPoints READ mountPoints)
    inline ByteArrayList mountPoints() const
    { return qvariant_cast< ByteArrayList >(property("MountPoints")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freedesktop {
    namespace UDisks2 {
      typedef ::OrgFreedesktopUDisks2FilesystemInterface Filesystem;
    }
  }
}
#endif
